### ISSUE TITLE
Cannot serve files from root (static_url="/" becomes "//")

### ISSUE THREAD

**Issue by blueyed** [rexzhang/asgi-middleware-static-file#3]
Using `static_url="/"` does not work, because it results in a prefix of `//` being looked for then:
https://github.com/rexzhang/asgi-middleware-static-file/blob/main/asgi_middleware_static_file/core.py#L53

My use case is serving files from both "/static" (with `static_url="/static`), but also `favicon.ico` from the root.

For this I've tried to wrap two `ASGIMiddlewareStaticFile` applications around the real app.

(`static_root_paths` is a separate folder, so this would not expose all files)

**Comment by blueyed** [comment]
> My use case is serving files from both "/static" (with `static_url="/static`), but also `favicon.ico` from the root.

For this to work it would also not have to return a 404 in case it is not found then, so that the wrapped application would handle it.

**Comment by rexzhang** [comment]
thanks for your response. I released a new version for this bug. please upgrade to version 0.4.0

**Comment by blueyed** [comment]
Thanks, closing then.
FWIW, I'm using a redirect now for favicon.ico, given that it would result in a 404 for all other urls then.

**Comment by rexzhang** [comment]
FYI, my solution:
```html
<!doctype html>
<html lang="zh-CN">
<head>
  <link rel="shortcut icon" href="[/static/img/emo-logo.png](view-source:https://eve.sgfans.org/static/img/emo-logo.png)">
</head>
...
```
